blank_issues_enabled: false
contact_links:
  - name: Lattice discussions
    url: https://github.com/jbatte47/lattice/discussions
    about: Please ask questions or propose ideas here instead of opening a new issue.
